---
settings:
  collections: collections.yaml
  templates: data/templates
  output: html
  size limit: 202400
  timeout: 90
  log_file: STDOUT
  log_level: debug
db:
  driver: SQLite3
  database: harvester.sqlite3
